// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<model$0.CaracterDetails | null>}
 */
export function GetCharacter(id) {
    return $Call.ByID(2785694556, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<model$0.CaracterPreview[]>}
 */
export function GetCharacterList() {
    return $Call.ByID(1838292004).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<model$0.CaracterDetails | null>}
 */
export function Greet(id) {
    return $Call.ByID(1085101608, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} jsonData
 * @returns {$CancellablePromise<model$0.CaracterDetails | null>}
 */
export function ImportCharacter(jsonData) {
    return $Call.ByID(1256427305, jsonData).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.CaracterDetails.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.CaracterPreview.createFrom;
const $$createType3 = $Create.Array($$createType2);
