// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CharacterSrv from "./charactersrv.js";
export {
    CharacterSrv
};
