// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Ambitions,
    Armour,
    Caracter,
    Career,
    Characteristic,
    Corruption,
    Description,
    Encumbrance,
    ExpPoints,
    FPoint,
    Movment,
    Party,
    Points,
    Prayer,
    Quality,
    RPoint,
    Spell,
    Status,
    Talent,
    Trapping,
    Weapon,
    Welth,
    Wounds
} from "./models.js";

import * as $models from "./models.js";

/**
 * TODO: implement BookVersion enum
 * @typedef {$models.BookVersion} BookVersion
 */

/**
 * TODO: implement class enum
 * @typedef {$models.Class} Class
 */

/**
 * TODO: implement Location enum
 * @typedef {$models.Location} Location
 */

/**
 * @typedef {$models.Psychology} Psychology
 */

/**
 * TODO: implement species enum
 * @typedef {$models.Species} Species
 */

/**
 * TODO: implement StatusTier enum
 * @typedef {$models.StatusTier} StatusTier
 */

/**
 * TODO: implement WeaponGroup enum
 * @typedef {$models.WeaponGroup} WeaponGroup
 */
