// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Ambitions,
    Armour,
    ArmourLocation,
    BookVersion,
    CaracterDetails,
    CaracterPreview,
    Career,
    Characteristic,
    Characteristics,
    Corruption,
    Description,
    Encumbrance,
    ExpPoints,
    FPoint,
    LearnedTalent,
    Movment,
    Party,
    Points,
    Prayer,
    Quality,
    RPoint,
    Skill,
    Spell,
    Status,
    StatusTier,
    Talent,
    Trapping,
    Weapon,
    Welth,
    Wounds
} from "./models.js";

import * as $models from "./models.js";

/**
 * @typedef {$models.Class} Class
 */

/**
 * @typedef {$models.Psychology} Psychology
 */

/**
 * @typedef {$models.Skills} Skills
 */

/**
 * @typedef {$models.Species} Species
 */

/**
 * @typedef {$models.WeaponGroup} WeaponGroup
 */
