// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";

export class Ambitions {
    /**
     * Creates a new Ambitions instance.
     * @param {Partial<Ambitions>} [$$source = {}] - The source object to create the Ambitions.
     */
    constructor($$source = {}) {
        if (!("ShortTerm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ShortTerm"] = "";
        }
        if (!("LongTerm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LongTerm"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ambitions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Ambitions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ambitions(/** @type {Partial<Ambitions>} */($$parsedSource));
    }
}

export class Armour {
    /**
     * Creates a new Armour instance.
     * @param {Partial<Armour>} [$$source = {}] - The source object to create the Armour.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Location" in $$source)) {
            /**
             * @member
             * @type {Location}
             */
            this["Location"] = "";
        }
        if (!("Encumbrance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Encumbrance"] = 0;
        }
        if (!("ArmourPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ArmourPoints"] = 0;
        }
        if (!("Qualities" in $$source)) {
            /**
             * @member
             * @type {Quality[]}
             */
            this["Qualities"] = [];
        }
        if (!("IsWorn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsWorn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Armour instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Armour}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Qualities" in $$parsedSource) {
            $$parsedSource["Qualities"] = $$createField4_0($$parsedSource["Qualities"]);
        }
        return new Armour(/** @type {Partial<Armour>} */($$parsedSource));
    }
}

/**
 * TODO: implement BookVersion enum
 * @typedef {string} BookVersion
 */

export class Caracter {
    /**
     * Creates a new Caracter instance.
     * @param {Partial<Caracter>} [$$source = {}] - The source object to create the Caracter.
     */
    constructor($$source = {}) {
        if (!("CaracterId" in $$source)) {
            /**
             * @member
             * @type {uuid$0.UUID}
             */
            this["CaracterId"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Species" in $$source)) {
            /**
             * @member
             * @type {Species}
             */
            this["Species"] = "";
        }
        if (!("Class" in $$source)) {
            /**
             * @member
             * @type {Class}
             */
            this["Class"] = "";
        }
        if (!("Career" in $$source)) {
            /**
             * @member
             * @type {Career}
             */
            this["Career"] = (new Career());
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["Status"] = (new Status());
        }
        if (!("Skills" in $$source)) {
            /**
             * @member
             * @type {Skills}
             */
            this["Skills"] = [];
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {Description}
             */
            this["Description"] = (new Description());
        }
        if (!("Talents" in $$source)) {
            /**
             * @member
             * @type {Talent[]}
             */
            this["Talents"] = [];
        }
        if (!("Characteristic" in $$source)) {
            /**
             * @member
             * @type {Characteristic}
             */
            this["Characteristic"] = (new Characteristic());
        }
        if (!("Movment" in $$source)) {
            /**
             * @member
             * @type {Movment}
             */
            this["Movment"] = (new Movment());
        }
        if (!("Ambitions" in $$source)) {
            /**
             * @member
             * @type {Ambitions}
             */
            this["Ambitions"] = (new Ambitions());
        }
        if (!("Party" in $$source)) {
            /**
             * @member
             * @type {Party | null}
             */
            this["Party"] = null;
        }
        if (!("Armour" in $$source)) {
            /**
             * @member
             * @type {Armour}
             */
            this["Armour"] = (new Armour());
        }
        if (!("Trappings" in $$source)) {
            /**
             * @member
             * @type {Trapping[]}
             */
            this["Trappings"] = [];
        }
        if (!("Encumbrance" in $$source)) {
            /**
             * @member
             * @type {Encumbrance}
             */
            this["Encumbrance"] = (new Encumbrance());
        }
        if (!("Welth" in $$source)) {
            /**
             * @member
             * @type {Welth}
             */
            this["Welth"] = (new Welth());
        }
        if (!("Wounds" in $$source)) {
            /**
             * @member
             * @type {Wounds}
             */
            this["Wounds"] = (new Wounds());
        }
        if (!("Weapons" in $$source)) {
            /**
             * @member
             * @type {Weapon[]}
             */
            this["Weapons"] = [];
        }
        if (!("Spells" in $$source)) {
            /**
             * @member
             * @type {Spell[]}
             */
            this["Spells"] = [];
        }
        if (!("Prayers" in $$source)) {
            /**
             * @member
             * @type {Prayer[]}
             */
            this["Prayers"] = [];
        }
        if (!("Sin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Sin"] = 0;
        }
        if (!("Corruption" in $$source)) {
            /**
             * @member
             * @type {Corruption}
             */
            this["Corruption"] = (new Corruption());
        }
        if (!("Psychology" in $$source)) {
            /**
             * @member
             * @type {Psychology}
             */
            this["Psychology"] = [];
        }
        if (!("Points" in $$source)) {
            /**
             * @member
             * @type {Points}
             */
            this["Points"] = (new Points());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Caracter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Caracter}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType10;
        const $$createField10_0 = $$createType11;
        const $$createField11_0 = $$createType12;
        const $$createField12_0 = $$createType14;
        const $$createField13_0 = $$createType15;
        const $$createField14_0 = $$createType17;
        const $$createField15_0 = $$createType18;
        const $$createField16_0 = $$createType19;
        const $$createField17_0 = $$createType20;
        const $$createField18_0 = $$createType22;
        const $$createField19_0 = $$createType24;
        const $$createField20_0 = $$createType26;
        const $$createField22_0 = $$createType27;
        const $$createField23_0 = $$createType28;
        const $$createField24_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Career" in $$parsedSource) {
            $$parsedSource["Career"] = $$createField4_0($$parsedSource["Career"]);
        }
        if ("Status" in $$parsedSource) {
            $$parsedSource["Status"] = $$createField5_0($$parsedSource["Status"]);
        }
        if ("Skills" in $$parsedSource) {
            $$parsedSource["Skills"] = $$createField6_0($$parsedSource["Skills"]);
        }
        if ("Description" in $$parsedSource) {
            $$parsedSource["Description"] = $$createField7_0($$parsedSource["Description"]);
        }
        if ("Talents" in $$parsedSource) {
            $$parsedSource["Talents"] = $$createField8_0($$parsedSource["Talents"]);
        }
        if ("Characteristic" in $$parsedSource) {
            $$parsedSource["Characteristic"] = $$createField9_0($$parsedSource["Characteristic"]);
        }
        if ("Movment" in $$parsedSource) {
            $$parsedSource["Movment"] = $$createField10_0($$parsedSource["Movment"]);
        }
        if ("Ambitions" in $$parsedSource) {
            $$parsedSource["Ambitions"] = $$createField11_0($$parsedSource["Ambitions"]);
        }
        if ("Party" in $$parsedSource) {
            $$parsedSource["Party"] = $$createField12_0($$parsedSource["Party"]);
        }
        if ("Armour" in $$parsedSource) {
            $$parsedSource["Armour"] = $$createField13_0($$parsedSource["Armour"]);
        }
        if ("Trappings" in $$parsedSource) {
            $$parsedSource["Trappings"] = $$createField14_0($$parsedSource["Trappings"]);
        }
        if ("Encumbrance" in $$parsedSource) {
            $$parsedSource["Encumbrance"] = $$createField15_0($$parsedSource["Encumbrance"]);
        }
        if ("Welth" in $$parsedSource) {
            $$parsedSource["Welth"] = $$createField16_0($$parsedSource["Welth"]);
        }
        if ("Wounds" in $$parsedSource) {
            $$parsedSource["Wounds"] = $$createField17_0($$parsedSource["Wounds"]);
        }
        if ("Weapons" in $$parsedSource) {
            $$parsedSource["Weapons"] = $$createField18_0($$parsedSource["Weapons"]);
        }
        if ("Spells" in $$parsedSource) {
            $$parsedSource["Spells"] = $$createField19_0($$parsedSource["Spells"]);
        }
        if ("Prayers" in $$parsedSource) {
            $$parsedSource["Prayers"] = $$createField20_0($$parsedSource["Prayers"]);
        }
        if ("Corruption" in $$parsedSource) {
            $$parsedSource["Corruption"] = $$createField22_0($$parsedSource["Corruption"]);
        }
        if ("Psychology" in $$parsedSource) {
            $$parsedSource["Psychology"] = $$createField23_0($$parsedSource["Psychology"]);
        }
        if ("Points" in $$parsedSource) {
            $$parsedSource["Points"] = $$createField24_0($$parsedSource["Points"]);
        }
        return new Caracter(/** @type {Partial<Caracter>} */($$parsedSource));
    }
}

export class Career {
    /**
     * Creates a new Career instance.
     * @param {Partial<Career>} [$$source = {}] - The source object to create the Career.
     */
    constructor($$source = {}) {
        if (!("Career" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Career"] = "";
        }
        if (!("CareerTier" in $$source)) {
            /**
             * between 1 and 4
             * @member
             * @type {number}
             */
            this["CareerTier"] = 0;
        }
        if (!("CareerPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CareerPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Career instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Career}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Career(/** @type {Partial<Career>} */($$parsedSource));
    }
}

export class Characteristic {
    /**
     * Creates a new Characteristic instance.
     * @param {Partial<Characteristic>} [$$source = {}] - The source object to create the Characteristic.
     */
    constructor($$source = {}) {
        if (!("Basic" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Basic"] = 0;
        }
        if (!("Advances" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Advances"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Characteristic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Characteristic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Characteristic(/** @type {Partial<Characteristic>} */($$parsedSource));
    }
}

/**
 * TODO: implement class enum
 * @typedef {string} Class
 */

export class Corruption {
    /**
     * Creates a new Corruption instance.
     * @param {Partial<Corruption>} [$$source = {}] - The source object to create the Corruption.
     */
    constructor($$source = {}) {
        if (!("Treshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Treshold"] = 0;
        }
        if (!("Current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Current"] = 0;
        }
        if (!("Mutations" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Mutations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Corruption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Corruption}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mutations" in $$parsedSource) {
            $$parsedSource["Mutations"] = $$createField2_0($$parsedSource["Mutations"]);
        }
        return new Corruption(/** @type {Partial<Corruption>} */($$parsedSource));
    }
}

export class Description {
    /**
     * Creates a new Description instance.
     * @param {Partial<Description>} [$$source = {}] - The source object to create the Description.
     */
    constructor($$source = {}) {
        if (!("Age" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Age"] = 0;
        }
        if (!("Height" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Height"] = "";
        }
        if (!("Hair" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Hair"] = "";
        }
        if (!("Eyes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Eyes"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Psychology" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Psychology"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Description instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Description}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Description(/** @type {Partial<Description>} */($$parsedSource));
    }
}

export class Encumbrance {
    /**
     * Creates a new Encumbrance instance.
     * @param {Partial<Encumbrance>} [$$source = {}] - The source object to create the Encumbrance.
     */
    constructor($$source = {}) {
        if (!("Weapons" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Weapons"] = 0;
        }
        if (!("Armour" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Armour"] = 0;
        }
        if (!("Trappings" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Trappings"] = 0;
        }
        if (!("Max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Max"] = 0;
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("Penalty" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Penalty"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Encumbrance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Encumbrance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Encumbrance(/** @type {Partial<Encumbrance>} */($$parsedSource));
    }
}

export class ExpPoints {
    /**
     * Creates a new ExpPoints instance.
     * @param {Partial<ExpPoints>} [$$source = {}] - The source object to create the ExpPoints.
     */
    constructor($$source = {}) {
        if (!("Current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Current"] = 0;
        }
        if (!("Spent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Spent"] = 0;
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExpPoints instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExpPoints}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExpPoints(/** @type {Partial<ExpPoints>} */($$parsedSource));
    }
}

export class FPoint {
    /**
     * Creates a new FPoint instance.
     * @param {Partial<FPoint>} [$$source = {}] - The source object to create the FPoint.
     */
    constructor($$source = {}) {
        if (!("FateMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FateMax"] = 0;
        }
        if (!("FateCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FateCurrent"] = 0;
        }
        if (!("FortuneMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FortuneMax"] = 0;
        }
        if (!("FortuneCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FortuneCurrent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FPoint(/** @type {Partial<FPoint>} */($$parsedSource));
    }
}

/**
 * TODO: implement Location enum
 * @typedef {string} Location
 */

export class Movment {
    /**
     * Creates a new Movment instance.
     * @param {Partial<Movment>} [$$source = {}] - The source object to create the Movment.
     */
    constructor($$source = {}) {
        if (!("Movment" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Movment"] = 0;
        }
        if (!("Walk" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Walk"] = 0;
        }
        if (!("Run" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Run"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Movment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Movment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Movment(/** @type {Partial<Movment>} */($$parsedSource));
    }
}

export class Party {
    /**
     * Creates a new Party instance.
     * @param {Partial<Party>} [$$source = {}] - The source object to create the Party.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Ambitions" in $$source)) {
            /**
             * @member
             * @type {Ambitions}
             */
            this["Ambitions"] = (new Ambitions());
        }
        if (!("Members" in $$source)) {
            /**
             * @member
             * @type {Caracter[]}
             */
            this["Members"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Party instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Party}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Ambitions" in $$parsedSource) {
            $$parsedSource["Ambitions"] = $$createField1_0($$parsedSource["Ambitions"]);
        }
        if ("Members" in $$parsedSource) {
            $$parsedSource["Members"] = $$createField2_0($$parsedSource["Members"]);
        }
        return new Party(/** @type {Partial<Party>} */($$parsedSource));
    }
}

export class Points {
    /**
     * Creates a new Points instance.
     * @param {Partial<Points>} [$$source = {}] - The source object to create the Points.
     */
    constructor($$source = {}) {
        if (!("Fate" in $$source)) {
            /**
             * @member
             * @type {FPoint}
             */
            this["Fate"] = (new FPoint());
        }
        if (!("Resilience" in $$source)) {
            /**
             * @member
             * @type {RPoint}
             */
            this["Resilience"] = (new RPoint());
        }
        if (!("Exp" in $$source)) {
            /**
             * @member
             * @type {ExpPoints}
             */
            this["Exp"] = (new ExpPoints());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Points instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Points}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType33;
        const $$createField1_0 = $$createType34;
        const $$createField2_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Fate" in $$parsedSource) {
            $$parsedSource["Fate"] = $$createField0_0($$parsedSource["Fate"]);
        }
        if ("Resilience" in $$parsedSource) {
            $$parsedSource["Resilience"] = $$createField1_0($$parsedSource["Resilience"]);
        }
        if ("Exp" in $$parsedSource) {
            $$parsedSource["Exp"] = $$createField2_0($$parsedSource["Exp"]);
        }
        return new Points(/** @type {Partial<Points>} */($$parsedSource));
    }
}

export class Prayer {
    /**
     * Creates a new Prayer instance.
     * @param {Partial<Prayer>} [$$source = {}] - The source object to create the Prayer.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {uuid$0.UUID}
             */
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Range" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Range"] = "";
        }
        if (!("Target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Target"] = "";
        }
        if (!("Duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Duration"] = "";
        }
        if (!("Effect" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Effect"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Prayer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Prayer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Prayer(/** @type {Partial<Prayer>} */($$parsedSource));
    }
}

/**
 * @typedef {string[]} Psychology
 */

export class Quality {
    /**
     * Creates a new Quality instance.
     * @param {Partial<Quality>} [$$source = {}] - The source object to create the Quality.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("IsFlaw" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsFlaw"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Quality instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Quality}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Quality(/** @type {Partial<Quality>} */($$parsedSource));
    }
}

export class RPoint {
    /**
     * Creates a new RPoint instance.
     * @param {Partial<RPoint>} [$$source = {}] - The source object to create the RPoint.
     */
    constructor($$source = {}) {
        if (!("ResilienceMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ResilienceMax"] = 0;
        }
        if (!("ResilienceMCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ResilienceMCurrent"] = 0;
        }
        if (!("ResolveMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ResolveMax"] = 0;
        }
        if (!("ResolveCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ResolveCurrent"] = 0;
        }
        if (!("Motive" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Motive"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RPoint(/** @type {Partial<RPoint>} */($$parsedSource));
    }
}

export class Skill {
    /**
     * Creates a new Skill instance.
     * @param {Partial<Skill>} [$$source = {}] - The source object to create the Skill.
     */
    constructor($$source = {}) {
        if (!("Characteristic" in $$source)) {
            /**
             * @member
             * @type {Characteristic}
             */
            this["Characteristic"] = (new Characteristic());
        }
        if (!("Basic" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Basic"] = 0;
        }
        if (!("Advances" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Advances"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Skill}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Characteristic" in $$parsedSource) {
            $$parsedSource["Characteristic"] = $$createField0_0($$parsedSource["Characteristic"]);
        }
        return new Skill(/** @type {Partial<Skill>} */($$parsedSource));
    }
}

/**
 * @typedef {Skill[]} Skills
 */

/**
 * TODO: implement species enum
 * @typedef {string} Species
 */

export class Spell {
    /**
     * Creates a new Spell instance.
     * @param {Partial<Spell>} [$$source = {}] - The source object to create the Spell.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {uuid$0.UUID}
             */
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("CastingNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CastingNumber"] = 0;
        }
        if (!("Range" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Range"] = "";
        }
        if (!("Target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Target"] = "";
        }
        if (!("Duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Duration"] = "";
        }
        if (!("Effect" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Effect"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spell instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Spell}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Spell(/** @type {Partial<Spell>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("Tier" in $$source)) {
            /**
             * @member
             * @type {StatusTier}
             */
            this["Tier"] = "";
        }
        if (!("Level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * TODO: implement StatusTier enum
 * @typedef {string} StatusTier
 */

export class Talent {
    /**
     * Creates a new Talent instance.
     * @param {Partial<Talent>} [$$source = {}] - The source object to create the Talent.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {uuid$0.UUID}
             */
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {BookVersion}
             */
            this["Version"] = "";
        }
        if (!("MaxLvl" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxLvl"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["test"] = undefined;
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Talent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Talent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Talent(/** @type {Partial<Talent>} */($$parsedSource));
    }
}

export class Trapping {
    /**
     * Creates a new Trapping instance.
     * @param {Partial<Trapping>} [$$source = {}] - The source object to create the Trapping.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Encumbrance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Encumbrance"] = 0;
        }
        if (!("Qualities" in $$source)) {
            /**
             * @member
             * @type {Quality[]}
             */
            this["Qualities"] = [];
        }
        if (!("IsWorn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsWorn"] = false;
        }
        if (!("IsStorage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsStorage"] = false;
        }
        if (!("StoreEnc" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["StoreEnc"] = 0;
        }
        if (!("FilledEnc" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FilledEnc"] = 0;
        }
        if (!("Trappings" in $$source)) {
            /**
             * @member
             * @type {Trapping[]}
             */
            this["Trappings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Trapping instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Trapping}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField7_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Qualities" in $$parsedSource) {
            $$parsedSource["Qualities"] = $$createField2_0($$parsedSource["Qualities"]);
        }
        if ("Trappings" in $$parsedSource) {
            $$parsedSource["Trappings"] = $$createField7_0($$parsedSource["Trappings"]);
        }
        return new Trapping(/** @type {Partial<Trapping>} */($$parsedSource));
    }
}

export class Weapon {
    /**
     * Creates a new Weapon instance.
     * @param {Partial<Weapon>} [$$source = {}] - The source object to create the Weapon.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Group" in $$source)) {
            /**
             * @member
             * @type {WeaponGroup}
             */
            this["Group"] = "";
        }
        if (!("Encumbrance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Encumbrance"] = 0;
        }
        if (!("Range_Reach" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Range_Reach"] = 0;
        }
        if (!("Damage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Damage"] = "";
        }
        if (!("Qualities" in $$source)) {
            /**
             * @member
             * @type {Quality}
             */
            this["Qualities"] = (new Quality());
        }
        if (!("IsWorn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsWorn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Weapon instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Weapon}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Qualities" in $$parsedSource) {
            $$parsedSource["Qualities"] = $$createField5_0($$parsedSource["Qualities"]);
        }
        return new Weapon(/** @type {Partial<Weapon>} */($$parsedSource));
    }
}

/**
 * TODO: implement WeaponGroup enum
 * @typedef {string} WeaponGroup
 */

/**
 * conversion 1GC = 20SS = 240D
 */
export class Welth {
    /**
     * Creates a new Welth instance.
     * @param {Partial<Welth>} [$$source = {}] - The source object to create the Welth.
     */
    constructor($$source = {}) {
        if (!("BrassPenny" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["BrassPenny"] = 0;
        }
        if (!("SilverShilling" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SilverShilling"] = 0;
        }
        if (!("GoldCrown" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["GoldCrown"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Welth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Welth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Welth(/** @type {Partial<Welth>} */($$parsedSource));
    }
}

export class Wounds {
    /**
     * Creates a new Wounds instance.
     * @param {Partial<Wounds>} [$$source = {}] - The source object to create the Wounds.
     */
    constructor($$source = {}) {
        if (!("Max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Max"] = 0;
        }
        if (!("Current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Current"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Wounds instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Wounds}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Wounds(/** @type {Partial<Wounds>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Quality.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Career.createFrom;
const $$createType3 = Status.createFrom;
var $$createType4 = /** @type {(...args: any[]) => any} */(function $$initCreateType4(...args) {
    if ($$createType4 === $$initCreateType4) {
        $$createType4 = $$createType6;
    }
    return $$createType4(...args);
});
const $$createType5 = Skill.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Description.createFrom;
const $$createType8 = Talent.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Characteristic.createFrom;
const $$createType11 = Movment.createFrom;
const $$createType12 = Ambitions.createFrom;
const $$createType13 = Party.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = Armour.createFrom;
const $$createType16 = Trapping.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = Encumbrance.createFrom;
const $$createType19 = Welth.createFrom;
const $$createType20 = Wounds.createFrom;
const $$createType21 = Weapon.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = Spell.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = Prayer.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = Corruption.createFrom;
var $$createType28 = /** @type {(...args: any[]) => any} */(function $$initCreateType28(...args) {
    if ($$createType28 === $$initCreateType28) {
        $$createType28 = $$createType29;
    }
    return $$createType28(...args);
});
const $$createType29 = $Create.Array($Create.Any);
const $$createType30 = Points.createFrom;
const $$createType31 = Caracter.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = FPoint.createFrom;
const $$createType34 = RPoint.createFrom;
const $$createType35 = ExpPoints.createFrom;
