/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/general/AppFooter.vue')['default']
    AppHeader: typeof import('./components/general/AppHeader.vue')['default']
    ArmourSilhouette: typeof import('./components/character/ArmourSilhouette.vue')['default']
    ArmourTable: typeof import('./components/character/ArmourTable.vue')['default']
    AwaitDialog: typeof import('./components/general/AwaitDialog.vue')['default']
    CharacterHeader: typeof import('./components/character/CharacterHeader.vue')['default']
    CharacteristicsTable: typeof import('./components/character/CharacteristicsTable.vue')['default']
    CharacterSheet: typeof import('./components/character/CharacterSheet.vue')['default']
    CompTwo: typeof import('./components/general/compTwo.vue')['default']
    ConfirmDialog: typeof import('./components/general/ConfirmDialog.vue')['default']
    Line: typeof import('./components/general/Line.vue')['default']
    MenuCard: typeof import('./components/general/MenuCard.vue')['default']
    PersonalInfoCard: typeof import('./components/character/PersonalInfoCard.vue')['default']
    PointsCard: typeof import('./components/character/PointsCard.vue')['default']
    PrayersTable: typeof import('./components/character/PrayersTable.vue')['default']
    ProductCard: typeof import('./components/general/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/general/Search.vue')['default']
    SkillSection: typeof import('./components/character/SkillSection.vue')['default']
    SnackbarProvider: typeof import('./components/general/SnackbarProvider.vue')['default']
    StatusCard: typeof import('./components/character/StatusCard.vue')['default']
    TabsLayout: typeof import('./components/general/TabsLayout.vue')['default']
    TalentList: typeof import('./components/character/TalentList.vue')['default']
    Test: typeof import('./components/general/Test.vue')['default']
    TrappingsTable: typeof import('./components/character/TrappingsTable.vue')['default']
    WeaponTable: typeof import('./components/character/WeaponTable.vue')['default']
  }
}
