/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/general/AppFooter.vue')['default']
    AppHeader: typeof import('./components/general/AppHeader.vue')['default']
    AwaitDialog: typeof import('./components/general/AwaitDialog.vue')['default']
    CompTwo: typeof import('./components/general/compTwo.vue')['default']
    ConfirmDialog: typeof import('./components/general/ConfirmDialog.vue')['default']
    Line: typeof import('./components/general/Line.vue')['default']
    MenuCard: typeof import('./components/general/MenuCard.vue')['default']
    ProductCard: typeof import('./components/general/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/general/Search.vue')['default']
    SnackbarProvider: typeof import('./components/general/SnackbarProvider.vue')['default']
    TabsLayout: typeof import('./components/general/TabsLayout.vue')['default']
    Test: typeof import('./components/general/Test.vue')['default']
  }
}
